//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhanSu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NhanVien()
        {
            this.HopDongs = new HashSet<HopDong>();
        }
    
        public int Id { get; set; }
        public string HoTen { get; set; }
        public string Email { get; set; }
        public string SDT { get; set; }
        public Nullable<bool> GioiTinh { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string QueQuan { get; set; }
        public string DanToc { get; set; }
        public Nullable<int> BacLuong { get; set; }
        public string ChuyenNganh { get; set; }
        public Nullable<int> IdTDHV { get; set; }
        public Nullable<int> IdPB { get; set; }
        public Nullable<int> IdTK { get; set; }
        public Nullable<decimal> Luong { get; set; }
        public string STK { get; set; }
        public string NganHang { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HopDong> HopDongs { get; set; }
        public virtual PhongBan PhongBan { get; set; }
        public virtual TrinhDoHocVan TrinhDoHocVan { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
